Update mlflow_ci.yaml

diff --git a/.github/workflows/mlflow_ci.yaml b/.github/workflows/mlflow_ci.yaml
--- a/.github/workflows/mlflow_ci.yaml
+++ b/.github/workflows/mlflow_ci.yaml
@@ -27,17 +27,10 @@ jobs:
         working-directory: MLProject
         run: python modelling.py
 
-      - name: Upload MLflow Artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: mlflow-artifacts
-          path: MLProject/mlruns
-          if-no-files-found: error
-
-      - name: DEBUG MLflow Folder
+      - name: DEBUG mlruns folder
         run: |
-          echo "===== MLProject/mlruns ====="
-          ls -R MLProject/mlruns || echo "No mlruns folder found"
+          echo "=== MLProject/mlruns Content ==="
+          ls -R MLProject/mlruns || echo "mlruns NOT FOUND"
 
       - name: Get Latest MLflow Model Path
         id: get_model
@@ -56,3 +49,25 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Build Docker Image from MLflow Model
+        run: |
+          echo "Building Docker image using: ${{ steps.get_model.outputs.model_path }}"
+          mlflow models build-docker \
+            -m "${{ steps.get_model.outputs.model_path }}"
+
+      - name: Find MLflow-built Docker Image
+        id: find_image
+        run: |
+          image=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep mlflow-pyfunc | head -n 1)
+          echo "Found image: $image"
+          echo "image=$image" >> $GITHUB_OUTPUT
+
+      - name: Tag Docker Image for Docker Hub
+        run: |
+          docker tag "${{ steps.find_image.outputs.image }}" \
+            ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
+
+      - name: Push Docker Image to Docker Hub
+        run: |
+          docker push ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
