Update mlflow_ci.yaml

diff --git a/.github/workflows/mlflow_ci.yaml b/.github/workflows/mlflow_ci.yaml
--- a/.github/workflows/mlflow_ci.yaml
+++ b/.github/workflows/mlflow_ci.yaml
@@ -35,7 +35,16 @@ jobs:
       - name: Get Latest MLflow Model Path
         id: get_model
         run: |
+          echo "Searching MLflow model folder..."
+          find MLProject/mlruns -type d -path "*/artifacts/model"
+
           model_path=$(find MLProject/mlruns -type d -path "*/artifacts/model" | sort | tail -n 1)
+
+          if [ -z "$model_path" ]; then
+            echo "No MLflow model folder found!"
+            exit 1
+          fi
+
           echo "Latest model path: $model_path"
           echo "model_path=$model_path" >> $GITHUB_OUTPUT
 
@@ -58,7 +67,12 @@ jobs:
 
       - name: Zip MLflow Model
         run: |
-          echo "Zipping model: ${{ steps.get_model.outputs.model_path }}"
+          if [ -z "${{ steps.get_model.outputs.model_path }}" ]; then
+            echo "Model path is empty. Cannot zip."
+            exit 1
+          fi
+
+          echo "Zipping: ${{ steps.get_model.outputs.model_path }}"
           zip -r mlflow_model.zip "${{ steps.get_model.outputs.model_path }}"
 
       - name: Upload MLflow Model Artifact
@@ -78,7 +92,6 @@ jobs:
         run: |
           docker tag "${{ steps.find_image.outputs.image }}" \
             ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
-
       - name: Push Docker Image to Docker Hub
         run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/gempa-model:latest
